name: Build and Deploy

on:
  push:
    branches:
      - master  # Set to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set to Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Ensure this is your correct build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages  # This is the branch GitHub Pages will use
          publish_dir: ./dist  # Adjust to your build output directory
          github_token: ${{ secrets.TOKEN }}

      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
